### ISSUE TITLE
Overview page error (cluster launched by tidb-operator)

### ISSUE THREAD

**Issue by c4pt0r** [pingcap-incubator/tidb-dashboard#459]
tidb-cluster.yaml:

```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
spec:
  version: v4.0.0-rc.1
  timezone: UTC
  pvReclaimPolicy: Delete
  pd:
    baseImage: pingcap/pd
    replicas: 1
    requests:
      storage: "1Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    replicas: 3
    requests:
      storage: "1Gi"
    config: {}
  tidb:
    baseImage: pingcap/tidb
    replicas: 2
    service:
      type: ClusterIP
    config: {}

```

![1](https://user-images.githubusercontent.com/773853/81381612-93641b80-913f-11ea-960e-9110a937b08f.png)
![2](https://user-images.githubusercontent.com/773853/81381620-952ddf00-913f-11ea-810e-69a51dca2dc5.png)
![3](https://user-images.githubusercontent.com/773853/81381627-96f7a280-913f-11ea-81c5-16024048760a.png)
